// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCharacterParams is parameters of getCharacter operation.
type GetCharacterParams struct {
	// The character name.
	Name string
}

func unpackGetCharacterParams(packed middleware.Parameters) (params GetCharacterParams) {
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "path",
		}
		params.Name = packed[key].(string)
	}
	return params
}

func decodeGetCharacterParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCharacterParams, _ error) {
	// Decode path: name.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "name",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetInsomniacsParams is parameters of getInsomniacs operation.
type GetInsomniacsParams struct {
	// If true, fetches all pages. If false or omitted, fetches only first page.
	IncludeAll OptBool `json:",omitempty,omitzero"`
}

func unpackGetInsomniacsParams(packed middleware.Parameters) (params GetInsomniacsParams) {
	{
		key := middleware.ParameterKey{
			Name: "include_all",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeAll = v.(OptBool)
		}
	}
	return params
}

func decodeGetInsomniacsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetInsomniacsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: include_all.
	{
		val := bool(false)
		params.IncludeAll.SetTo(val)
	}
	// Decode query: include_all.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_all",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeAllVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeAllVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeAll.SetTo(paramsDotIncludeAllVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_all",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetPowerGamersParams is parameters of getPowerGamers operation.
type GetPowerGamersParams struct {
	// If true, fetches all pages. If false or omitted, fetches only first page.
	IncludeAll OptBool `json:",omitempty,omitzero"`
}

func unpackGetPowerGamersParams(packed middleware.Parameters) (params GetPowerGamersParams) {
	{
		key := middleware.ParameterKey{
			Name: "include_all",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeAll = v.(OptBool)
		}
	}
	return params
}

func decodeGetPowerGamersParams(args [0]string, argsEscaped bool, r *http.Request) (params GetPowerGamersParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: include_all.
	{
		val := bool(false)
		params.IncludeAll.SetTo(val)
	}
	// Decode query: include_all.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_all",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeAllVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeAllVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeAll.SetTo(paramsDotIncludeAllVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_all",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
