// Code generated by ogen, DO NOT EDIT.
package api

type GetCharacterRes interface {
	getCharacterRes()
}

type GetGuildRes interface {
	getGuildRes()
}

type GetInsomniacsRes interface {
	getInsomniacsRes()
}

type GetPowerGamersRes interface {
	getPowerGamersRes()
}

type GetWhoIsOnlineRes interface {
	getWhoIsOnlineRes()
}
