// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCharacter implements getCharacter operation.
	//
	// Fetches and returns character information from miracle74.com.
	//
	// GET /characters/{name}
	GetCharacter(ctx context.Context, params GetCharacterParams) (GetCharacterRes, error)
	// GetGuild implements getGuild operation.
	//
	// Fetches and returns guild information including all members.
	//
	// GET /guilds/{guildId}
	GetGuild(ctx context.Context, params GetGuildParams) (GetGuildRes, error)
	// GetHealth implements getHealth operation.
	//
	// Returns the current health status of the API.
	//
	// GET /health
	GetHealth(ctx context.Context) (*HealthResponse, error)
	// GetInsomniacs implements getInsomniacs operation.
	//
	// Fetches and returns insomniacs (players with most online time). By default returns first page only,
	//  use include_all=true for all pages.
	//
	// GET /insomniacs
	GetInsomniacs(ctx context.Context, params GetInsomniacsParams) (GetInsomniacsRes, error)
	// GetPowerGamers implements getPowerGamers operation.
	//
	// Fetches and returns power gamers. By default returns first page only, use include_all=true for all
	// pages. Can filter by time period and vocation.
	//
	// GET /powergamers
	GetPowerGamers(ctx context.Context, params GetPowerGamersParams) (GetPowerGamersRes, error)
	// GetWhoIsOnline implements getWhoIsOnline operation.
	//
	// Fetches and returns list of players currently online. Can be sorted by name, level, or vocation.
	//
	// GET /whoisonline
	GetWhoIsOnline(ctx context.Context, params GetWhoIsOnlineParams) (GetWhoIsOnlineRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
