// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCharacter implements getCharacter operation.
//
// Fetches and returns character information from miracle74.com.
//
// GET /characters/{name}
func (UnimplementedHandler) GetCharacter(ctx context.Context, params GetCharacterParams) (r GetCharacterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGuild implements getGuild operation.
//
// Fetches and returns guild information including all members.
//
// GET /guilds/{guildId}
func (UnimplementedHandler) GetGuild(ctx context.Context, params GetGuildParams) (r GetGuildRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Returns the current health status of the API.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInsomniacs implements getInsomniacs operation.
//
// Fetches and returns insomniacs (players with most online time). By default returns first page only,
//
//	use include_all=true for all pages.
//
// GET /insomniacs
func (UnimplementedHandler) GetInsomniacs(ctx context.Context, params GetInsomniacsParams) (r GetInsomniacsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPowerGamers implements getPowerGamers operation.
//
// Fetches and returns power gamers. By default returns first page only, use include_all=true for all
// pages. Can filter by time period and vocation.
//
// GET /powergamers
func (UnimplementedHandler) GetPowerGamers(ctx context.Context, params GetPowerGamersParams) (r GetPowerGamersRes, _ error) {
	return r, ht.ErrNotImplemented
}
