// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCharacterParams is parameters of getCharacter operation.
type GetCharacterParams struct {
	// The character name.
	Name string
}

func unpackGetCharacterParams(packed middleware.Parameters) (params GetCharacterParams) {
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "path",
		}
		params.Name = packed[key].(string)
	}
	return params
}

func decodeGetCharacterParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCharacterParams, _ error) {
	// Decode path: name.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "name",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetGuildParams is parameters of getGuild operation.
type GetGuildParams struct {
	// The guild ID from the miracle74.com website.
	GuildId int
}

func unpackGetGuildParams(packed middleware.Parameters) (params GetGuildParams) {
	{
		key := middleware.ParameterKey{
			Name: "guildId",
			In:   "path",
		}
		params.GuildId = packed[key].(int)
	}
	return params
}

func decodeGetGuildParams(args [1]string, argsEscaped bool, r *http.Request) (params GetGuildParams, _ error) {
	// Decode path: guildId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "guildId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.GuildId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "guildId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetInsomniacsParams is parameters of getInsomniacs operation.
type GetInsomniacsParams struct {
	// If true, fetches all pages. If false or omitted, fetches only first page.
	IncludeAll OptBool `json:",omitempty,omitzero"`
}

func unpackGetInsomniacsParams(packed middleware.Parameters) (params GetInsomniacsParams) {
	{
		key := middleware.ParameterKey{
			Name: "include_all",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeAll = v.(OptBool)
		}
	}
	return params
}

func decodeGetInsomniacsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetInsomniacsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: include_all.
	{
		val := bool(false)
		params.IncludeAll.SetTo(val)
	}
	// Decode query: include_all.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_all",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeAllVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeAllVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeAll.SetTo(paramsDotIncludeAllVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_all",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetPowerGamersParams is parameters of getPowerGamers operation.
type GetPowerGamersParams struct {
	// If true, fetches all pages. If false or omitted, fetches only first page.
	IncludeAll OptBool `json:",omitempty,omitzero"`
	// Time period for power gamers list.
	List OptGetPowerGamersList `json:",omitempty,omitzero"`
	// Filter by vocation. Values:
	// - "" (empty/omitted): All vocations
	// - "0": No Vocation
	// - "1": Sorcerers
	// - "2": Druids
	// - "3": Paladins
	// - "4": Knights.
	Vocation OptGetPowerGamersVocation `json:",omitempty,omitzero"`
}

func unpackGetPowerGamersParams(packed middleware.Parameters) (params GetPowerGamersParams) {
	{
		key := middleware.ParameterKey{
			Name: "include_all",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeAll = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "list",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.List = v.(OptGetPowerGamersList)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "vocation",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Vocation = v.(OptGetPowerGamersVocation)
		}
	}
	return params
}

func decodeGetPowerGamersParams(args [0]string, argsEscaped bool, r *http.Request) (params GetPowerGamersParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: include_all.
	{
		val := bool(false)
		params.IncludeAll.SetTo(val)
	}
	// Decode query: include_all.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_all",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeAllVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeAllVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeAll.SetTo(paramsDotIncludeAllVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_all",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: list.
	{
		val := GetPowerGamersList("today")
		params.List.SetTo(val)
	}
	// Decode query: list.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "list",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotListVal GetPowerGamersList
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotListVal = GetPowerGamersList(c)
					return nil
				}(); err != nil {
					return err
				}
				params.List.SetTo(paramsDotListVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.List.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "list",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: vocation.
	{
		val := GetPowerGamersVocation("")
		params.Vocation.SetTo(val)
	}
	// Decode query: vocation.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "vocation",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotVocationVal GetPowerGamersVocation
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotVocationVal = GetPowerGamersVocation(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Vocation.SetTo(paramsDotVocationVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Vocation.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "vocation",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetWhoIsOnlineParams is parameters of getWhoIsOnline operation.
type GetWhoIsOnlineParams struct {
	// Sort order for the online players list.
	Order OptGetWhoIsOnlineOrder `json:",omitempty,omitzero"`
}

func unpackGetWhoIsOnlineParams(packed middleware.Parameters) (params GetWhoIsOnlineParams) {
	{
		key := middleware.ParameterKey{
			Name: "order",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Order = v.(OptGetWhoIsOnlineOrder)
		}
	}
	return params
}

func decodeGetWhoIsOnlineParams(args [0]string, argsEscaped bool, r *http.Request) (params GetWhoIsOnlineParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: order.
	{
		val := GetWhoIsOnlineOrder("name")
		params.Order.SetTo(val)
	}
	// Decode query: order.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "order",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOrderVal GetWhoIsOnlineOrder
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOrderVal = GetWhoIsOnlineOrder(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Order.SetTo(paramsDotOrderVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Order.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
