// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CharacterResponse
type CharacterResponse struct {
	// Character name.
	Name string `json:"name"`
	// Character sex.
	Sex string `json:"sex"`
	// Character vocation.
	Vocation OptString `json:"vocation"`
	// Character level.
	Level OptInt `json:"level"`
	// Character residence city.
	Residence OptString `json:"residence"`
	// Guild name.
	Guild OptString `json:"guild"`
	// Rank within the guild.
	GuildRank OptString `json:"guild_rank"`
	// Guild profile URL.
	GuildURL OptString `json:"guild_url"`
	// Last login timestamp.
	LastLogin OptDateTime `json:"last_login"`
	// Premium account status.
	IsPremium bool `json:"is_premium"`
	// Country code.
	Country OptString `json:"country"`
	// Recent character deaths.
	Deaths []Death `json:"deaths"`
}

// GetName returns the value of Name.
func (s *CharacterResponse) GetName() string {
	return s.Name
}

// GetSex returns the value of Sex.
func (s *CharacterResponse) GetSex() string {
	return s.Sex
}

// GetVocation returns the value of Vocation.
func (s *CharacterResponse) GetVocation() OptString {
	return s.Vocation
}

// GetLevel returns the value of Level.
func (s *CharacterResponse) GetLevel() OptInt {
	return s.Level
}

// GetResidence returns the value of Residence.
func (s *CharacterResponse) GetResidence() OptString {
	return s.Residence
}

// GetGuild returns the value of Guild.
func (s *CharacterResponse) GetGuild() OptString {
	return s.Guild
}

// GetGuildRank returns the value of GuildRank.
func (s *CharacterResponse) GetGuildRank() OptString {
	return s.GuildRank
}

// GetGuildURL returns the value of GuildURL.
func (s *CharacterResponse) GetGuildURL() OptString {
	return s.GuildURL
}

// GetLastLogin returns the value of LastLogin.
func (s *CharacterResponse) GetLastLogin() OptDateTime {
	return s.LastLogin
}

// GetIsPremium returns the value of IsPremium.
func (s *CharacterResponse) GetIsPremium() bool {
	return s.IsPremium
}

// GetCountry returns the value of Country.
func (s *CharacterResponse) GetCountry() OptString {
	return s.Country
}

// GetDeaths returns the value of Deaths.
func (s *CharacterResponse) GetDeaths() []Death {
	return s.Deaths
}

// SetName sets the value of Name.
func (s *CharacterResponse) SetName(val string) {
	s.Name = val
}

// SetSex sets the value of Sex.
func (s *CharacterResponse) SetSex(val string) {
	s.Sex = val
}

// SetVocation sets the value of Vocation.
func (s *CharacterResponse) SetVocation(val OptString) {
	s.Vocation = val
}

// SetLevel sets the value of Level.
func (s *CharacterResponse) SetLevel(val OptInt) {
	s.Level = val
}

// SetResidence sets the value of Residence.
func (s *CharacterResponse) SetResidence(val OptString) {
	s.Residence = val
}

// SetGuild sets the value of Guild.
func (s *CharacterResponse) SetGuild(val OptString) {
	s.Guild = val
}

// SetGuildRank sets the value of GuildRank.
func (s *CharacterResponse) SetGuildRank(val OptString) {
	s.GuildRank = val
}

// SetGuildURL sets the value of GuildURL.
func (s *CharacterResponse) SetGuildURL(val OptString) {
	s.GuildURL = val
}

// SetLastLogin sets the value of LastLogin.
func (s *CharacterResponse) SetLastLogin(val OptDateTime) {
	s.LastLogin = val
}

// SetIsPremium sets the value of IsPremium.
func (s *CharacterResponse) SetIsPremium(val bool) {
	s.IsPremium = val
}

// SetCountry sets the value of Country.
func (s *CharacterResponse) SetCountry(val OptString) {
	s.Country = val
}

// SetDeaths sets the value of Deaths.
func (s *CharacterResponse) SetDeaths(val []Death) {
	s.Deaths = val
}

func (*CharacterResponse) getCharacterRes() {}

// Ref: #/components/schemas/Death
type Death struct {
	// Death date and time.
	Date string `json:"date"`
	// Level at time of death.
	Level int `json:"level"`
	// What killed the character.
	KilledBy string `json:"killed_by"`
}

// GetDate returns the value of Date.
func (s *Death) GetDate() string {
	return s.Date
}

// GetLevel returns the value of Level.
func (s *Death) GetLevel() int {
	return s.Level
}

// GetKilledBy returns the value of KilledBy.
func (s *Death) GetKilledBy() string {
	return s.KilledBy
}

// SetDate sets the value of Date.
func (s *Death) SetDate(val string) {
	s.Date = val
}

// SetLevel sets the value of Level.
func (s *Death) SetLevel(val int) {
	s.Level = val
}

// SetKilledBy sets the value of KilledBy.
func (s *Death) SetKilledBy(val string) {
	s.KilledBy = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Error code.
	Error string `json:"error"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) getInsomniacsRes()  {}
func (*ErrorResponse) getPowerGamersRes() {}

type GetCharacterInternalServerError ErrorResponse

func (*GetCharacterInternalServerError) getCharacterRes() {}

type GetCharacterNotFound ErrorResponse

func (*GetCharacterNotFound) getCharacterRes() {}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	Status    HealthResponseStatus `json:"status"`
	Timestamp time.Time            `json:"timestamp"`
	Version   string               `json:"version"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() HealthResponseStatus {
	return s.Status
}

// GetTimestamp returns the value of Timestamp.
func (s *HealthResponse) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetVersion returns the value of Version.
func (s *HealthResponse) GetVersion() string {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val HealthResponseStatus) {
	s.Status = val
}

// SetTimestamp sets the value of Timestamp.
func (s *HealthResponse) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetVersion sets the value of Version.
func (s *HealthResponse) SetVersion(val string) {
	s.Version = val
}

type HealthResponseStatus string

const (
	HealthResponseStatusHealthy  HealthResponseStatus = "healthy"
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
)

// AllValues returns all HealthResponseStatus values.
func (HealthResponseStatus) AllValues() []HealthResponseStatus {
	return []HealthResponseStatus{
		HealthResponseStatusHealthy,
		HealthResponseStatusDegraded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthResponseStatusHealthy:
		return []byte(s), nil
	case HealthResponseStatusDegraded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthResponseStatus) UnmarshalText(data []byte) error {
	switch HealthResponseStatus(data) {
	case HealthResponseStatusHealthy:
		*s = HealthResponseStatusHealthy
		return nil
	case HealthResponseStatusDegraded:
		*s = HealthResponseStatusDegraded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Insomniac
type Insomniac struct {
	// Insomniac rank.
	Rank int `json:"rank"`
	// Character name.
	Name string `json:"name"`
	// Country code.
	Country OptString `json:"country"`
	// Character vocation.
	Vocation string `json:"vocation"`
	// Character level.
	Level int `json:"level"`
	// Time spent online.
	TimeOnline string `json:"time_online"`
}

// GetRank returns the value of Rank.
func (s *Insomniac) GetRank() int {
	return s.Rank
}

// GetName returns the value of Name.
func (s *Insomniac) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *Insomniac) GetCountry() OptString {
	return s.Country
}

// GetVocation returns the value of Vocation.
func (s *Insomniac) GetVocation() string {
	return s.Vocation
}

// GetLevel returns the value of Level.
func (s *Insomniac) GetLevel() int {
	return s.Level
}

// GetTimeOnline returns the value of TimeOnline.
func (s *Insomniac) GetTimeOnline() string {
	return s.TimeOnline
}

// SetRank sets the value of Rank.
func (s *Insomniac) SetRank(val int) {
	s.Rank = val
}

// SetName sets the value of Name.
func (s *Insomniac) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *Insomniac) SetCountry(val OptString) {
	s.Country = val
}

// SetVocation sets the value of Vocation.
func (s *Insomniac) SetVocation(val string) {
	s.Vocation = val
}

// SetLevel sets the value of Level.
func (s *Insomniac) SetLevel(val int) {
	s.Level = val
}

// SetTimeOnline sets the value of TimeOnline.
func (s *Insomniac) SetTimeOnline(val string) {
	s.TimeOnline = val
}

// Ref: #/components/schemas/InsomniacsResponse
type InsomniacsResponse struct {
	// List of all insomniacs.
	Insomniacs []Insomniac `json:"insomniacs"`
	// Total number of insomniacs.
	Total int `json:"total"`
}

// GetInsomniacs returns the value of Insomniacs.
func (s *InsomniacsResponse) GetInsomniacs() []Insomniac {
	return s.Insomniacs
}

// GetTotal returns the value of Total.
func (s *InsomniacsResponse) GetTotal() int {
	return s.Total
}

// SetInsomniacs sets the value of Insomniacs.
func (s *InsomniacsResponse) SetInsomniacs(val []Insomniac) {
	s.Insomniacs = val
}

// SetTotal sets the value of Total.
func (s *InsomniacsResponse) SetTotal(val int) {
	s.Total = val
}

func (*InsomniacsResponse) getInsomniacsRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PowerGamer
type PowerGamer struct {
	// Power gamer rank.
	Rank int `json:"rank"`
	// Character name.
	Name string `json:"name"`
	// Character vocation.
	Vocation string `json:"vocation"`
	// Character level.
	Level int `json:"level"`
	// Levels gained today.
	Today int `json:"today"`
}

// GetRank returns the value of Rank.
func (s *PowerGamer) GetRank() int {
	return s.Rank
}

// GetName returns the value of Name.
func (s *PowerGamer) GetName() string {
	return s.Name
}

// GetVocation returns the value of Vocation.
func (s *PowerGamer) GetVocation() string {
	return s.Vocation
}

// GetLevel returns the value of Level.
func (s *PowerGamer) GetLevel() int {
	return s.Level
}

// GetToday returns the value of Today.
func (s *PowerGamer) GetToday() int {
	return s.Today
}

// SetRank sets the value of Rank.
func (s *PowerGamer) SetRank(val int) {
	s.Rank = val
}

// SetName sets the value of Name.
func (s *PowerGamer) SetName(val string) {
	s.Name = val
}

// SetVocation sets the value of Vocation.
func (s *PowerGamer) SetVocation(val string) {
	s.Vocation = val
}

// SetLevel sets the value of Level.
func (s *PowerGamer) SetLevel(val int) {
	s.Level = val
}

// SetToday sets the value of Today.
func (s *PowerGamer) SetToday(val int) {
	s.Today = val
}

// Ref: #/components/schemas/PowerGamersResponse
type PowerGamersResponse struct {
	// List of all power gamers.
	PowerGamers []PowerGamer `json:"power_gamers"`
	// Total number of power gamers.
	Total int `json:"total"`
}

// GetPowerGamers returns the value of PowerGamers.
func (s *PowerGamersResponse) GetPowerGamers() []PowerGamer {
	return s.PowerGamers
}

// GetTotal returns the value of Total.
func (s *PowerGamersResponse) GetTotal() int {
	return s.Total
}

// SetPowerGamers sets the value of PowerGamers.
func (s *PowerGamersResponse) SetPowerGamers(val []PowerGamer) {
	s.PowerGamers = val
}

// SetTotal sets the value of Total.
func (s *PowerGamersResponse) SetTotal(val int) {
	s.Total = val
}

func (*PowerGamersResponse) getPowerGamersRes() {}
