// Code generated by ogen, DO NOT EDIT.
package api

type GetCharacterRes interface {
	getCharacterRes()
}

type GetInsomniacsRes interface {
	getInsomniacsRes()
}

type GetPowerGamersRes interface {
	getPowerGamersRes()
}
