// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCharacterOperation   OperationName = "GetCharacter"
	GetGuildOperation       OperationName = "GetGuild"
	GetHealthOperation      OperationName = "GetHealth"
	GetInsomniacsOperation  OperationName = "GetInsomniacs"
	GetPowerGamersOperation OperationName = "GetPowerGamers"
	GetWhoIsOnlineOperation OperationName = "GetWhoIsOnline"
)
